name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: scripts
      - name: Install vint
        run: |
          pipx install vim-vint || pip install --user vim-vint || true
      - name: Run vint
        run: |
          if command -v vint >/dev/null 2>&1; then vint .vimrc || true; else echo "vint not installed"; fi
